# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-12 13:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Multiplex',
            fields=[
                ('multi_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('storage', models.CharField(max_length=200)),
                ('mdsum', models.CharField(max_length=200)),
                ('barcode', models.CharField(max_length=1000)),
                ('read_type', models.CharField(choices=[(b'SR', b'Single'), (b'PR', b'Paired')], max_length=2)),
                ('read_length', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('antibody', models.CharField(max_length=20)),
                ('celltype', models.CharField(max_length=20)),
                ('comments', models.CharField(max_length=200)),
                ('descr', models.CharField(max_length=200)),
                ('exptype', models.CharField(max_length=20)),
                ('genotype', models.CharField(max_length=10)),
                ('organism', models.CharField(max_length=20)),
                ('preparation_type', models.CharField(max_length=200)),
                ('sample_id', models.IntegerField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=20)),
                ('tissue_type', models.CharField(max_length=20)),
                ('treatment', models.CharField(max_length=200)),
                ('multi', models.ManyToManyField(blank=True, null=True, to='ngs.Multiplex')),
            ],
        ),
        migrations.CreateModel(
            name='Scientist',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='sample',
            name='scientist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ngs.Scientist'),
        ),
    ]
