# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-12 13:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multiplex',
            name='barcode',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='multiplex',
            name='mdsum',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='multiplex',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='multiplex',
            name='read_length',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='multiplex',
            name='read_type',
            field=models.CharField(choices=[(b'SR', b'Single'), (b'PR', b'Paired')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='multiplex',
            name='storage',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
