# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-13 06:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngs', '0002_auto_20160412_1327'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flowlane',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('storage', models.CharField(max_length=200, null=True)),
                ('mdsum', models.CharField(max_length=200, null=True)),
                ('read_type', models.CharField(choices=[(b'SR', b'Single'), (b'PR', b'Paired')], max_length=2, null=True)),
                ('read_length', models.IntegerField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='sample',
            name='multi',
        ),
        migrations.AddField(
            model_name='sample',
            name='barcode',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='Multiplex',
        ),
        migrations.AddField(
            model_name='sample',
            name='flowlane',
            field=models.ManyToManyField(blank=True, null=True, to='ngs.Flowlane'),
        ),
    ]
